#!/bin/bash
# source from 
# https://stackoverflow.com/questions/9283472/command-to-remove-all-npm-modules-globally
sudo npm list -g --depth=0. | awk -F ' ' '{print $2}' | awk -F '@' '{print $1}'  | sudo xargs npm remove -g
